#!/bin/bash
set -x

start=${1:-start}

kill_pid() {
	[ -e $1 ] && (kill -3 $(cat $1); rm $1)
}
PID_IOC=./pid_ioc
PID_HTS=./pid_hts

kill_pid $PID_IOC
kill_pid $PID_HTS

if [ "x$start" = "xstart" ]; then
    rm -f records.dbl
# run the htstream wrapper on control socket 8843
	procServ -L htstream_wrapper.log -l 8844 -P 8843 -p $PID_HTS ./scripts/wait_ioc_and_run_htstream_wrapper
# run the IOC on control socket 8841
	procServ -L ioc.log -l 8842 -P 8841 -p $PID_IOC ./scripts/run_ioc
fi
